#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# validate GraphQL schema
./vendor/bin/sail artisan lighthouse:validate-schema

# run static analysis
./vendor/bin/sail composer analyse

# run tests
./vendor/bin/sail artisan test --without-tty -pqn --recreate-databases

# lint staged files
yarn lint-staged
